"""
drf-spectacular integration for drf-simple-api-errors.

Provides a postprocessing hook that injects standardized error response
schemas into the OpenAPI schema generated by drf-spectacular.

For more on drf-spectacular postprocessing hooks, see:
https://drf-spectacular.readthedocs.io/en/latest/customization.html#postprocessing-hooks
"""

from drf_simple_api_errors import utils
from drf_simple_api_errors.settings import api_settings


def build_error_component_schemas():
    """
    Build OpenAPI component schemas for the standardized error response.

    Returns a dict with two schemas (``APIError`` and ``InvalidParam``),
    with property names adjusted for the current ``CAMELIZE`` setting.

    Can be used standalone to retrieve the component schemas for use
    in custom postprocessing hooks or ``@extend_schema`` overrides::

        from drf_simple_api_errors.integrations.spectacular import (
            build_error_component_schemas,
        )

        schemas = build_error_component_schemas()
        # schemas["APIError"], schemas["InvalidParam"]
    """
    invalid_params_key = utils.camelize("invalid_params")

    return {
        "APIError": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string",
                    "description": ("A brief summary that describes the problem type."),
                },
                "detail": {
                    "type": "array",
                    "items": {"type": "string"},
                    "nullable": True,
                    "description": (
                        "A list of specific explanations related to the problem."
                    ),
                },
                invalid_params_key: {
                    "type": "array",
                    "items": {"$ref": "#/components/schemas/InvalidParam"},
                    "nullable": True,
                    "description": (
                        "A list of invalid parameters with their error details."
                    ),
                },
            },
            "required": ["title"],
        },
        "InvalidParam": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": ("The name of the invalid parameter."),
                },
                "reason": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": ("A list of reasons why the parameter is invalid."),
                },
            },
            "required": ["name", "reason"],
        },
    }


def build_error_response_object():
    """
    Build a reusable OpenAPI response object referencing the
    ``APIError`` schema component.

    Primarily consumed by :func:`postprocess_schema_inject_errors`. Exposed
    publicly for authors of custom postprocessing hooks who need the same
    raw OpenAPI response shape.

    For per-view overrides, use drf-spectacular's ``@extend_schema`` with a
    serializer or ``OpenApiResponse`` instead — that is the supported path
    for view-level customization.
    """
    return {
        "content": {
            "application/json": {
                "schema": {"$ref": "#/components/schemas/APIError"},
            },
        },
    }


def postprocess_schema_inject_errors(result, generator, request=None, public=True):
    """
    drf-spectacular postprocessing hook.

    Injects ``APIError`` and ``InvalidParam`` component schemas and adds
    error responses to all operations that do not already define them.

    Which status codes are injected is controlled by the
    ``SPECTACULAR_ERROR_STATUS_CODES`` setting. To override error
    responses on a specific view, use ``@extend_schema``::

        from drf_spectacular.utils import extend_schema

        @extend_schema(
            responses={
                404: {"description": "Book not found"},
            },
        )
        def retrieve(self, request, pk=None):
            ...

    Existing responses defined via ``@extend_schema`` are never
    overwritten by this hook.
    """
    # Inject component schemas (do not overwrite user-defined ones).
    schemas = result.setdefault("components", {}).setdefault("schemas", {})
    for name, schema in build_error_component_schemas().items():
        schemas.setdefault(name, schema)

    # Inject error responses into each operation.
    error_status_codes = api_settings.SPECTACULAR_ERROR_STATUS_CODES
    if not error_status_codes:
        return result

    error_response = build_error_response_object()
    for _path, methods in result.get("paths", {}).items():
        for _method, operation in methods.items():
            if not isinstance(operation, dict) or "responses" not in operation:
                continue
            responses = operation["responses"]
            for status_code, description in error_status_codes.items():
                if status_code not in responses:
                    responses[status_code] = {
                        "description": description,
                        **error_response,
                    }

    return result
